// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/nicobellanich/migroblogging-platform/internal/domain"
)

// MockIMessageRepository is a mock of IMessageRepository interface.
type MockIMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIMessageRepositoryMockRecorder
}

// MockIMessageRepositoryMockRecorder is the mock recorder for MockIMessageRepository.
type MockIMessageRepositoryMockRecorder struct {
	mock *MockIMessageRepository
}

// NewMockIMessageRepository creates a new mock instance.
func NewMockIMessageRepository(ctrl *gomock.Controller) *MockIMessageRepository {
	mock := &MockIMessageRepository{ctrl: ctrl}
	mock.recorder = &MockIMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMessageRepository) EXPECT() *MockIMessageRepositoryMockRecorder {
	return m.recorder
}

// LoadAllByUser mocks base method.
func (m *MockIMessageRepository) LoadAllByUser(arg0 string) ([]domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAllByUser", arg0)
	ret0, _ := ret[0].([]domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAllByUser indicates an expected call of LoadAllByUser.
func (mr *MockIMessageRepositoryMockRecorder) LoadAllByUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAllByUser", reflect.TypeOf((*MockIMessageRepository)(nil).LoadAllByUser), arg0)
}

// Save mocks base method.
func (m *MockIMessageRepository) Save(arg0 *domain.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIMessageRepositoryMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIMessageRepository)(nil).Save), arg0)
}

// MockIFollowersRepository is a mock of IFollowersRepository interface.
type MockIFollowersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIFollowersRepositoryMockRecorder
}

// MockIFollowersRepositoryMockRecorder is the mock recorder for MockIFollowersRepository.
type MockIFollowersRepositoryMockRecorder struct {
	mock *MockIFollowersRepository
}

// NewMockIFollowersRepository creates a new mock instance.
func NewMockIFollowersRepository(ctrl *gomock.Controller) *MockIFollowersRepository {
	mock := &MockIFollowersRepository{ctrl: ctrl}
	mock.recorder = &MockIFollowersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFollowersRepository) EXPECT() *MockIFollowersRepositoryMockRecorder {
	return m.recorder
}

// LoadFollowersByUser mocks base method.
func (m *MockIFollowersRepository) LoadFollowersByUser(arg0 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadFollowersByUser", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadFollowersByUser indicates an expected call of LoadFollowersByUser.
func (mr *MockIFollowersRepositoryMockRecorder) LoadFollowersByUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadFollowersByUser", reflect.TypeOf((*MockIFollowersRepository)(nil).LoadFollowersByUser), arg0)
}

// Save mocks base method.
func (m *MockIFollowersRepository) Save(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIFollowersRepositoryMockRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIFollowersRepository)(nil).Save), arg0, arg1)
}

// MockIUsersRepository is a mock of IUsersRepository interface.
type MockIUsersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUsersRepositoryMockRecorder
}

// MockIUsersRepositoryMockRecorder is the mock recorder for MockIUsersRepository.
type MockIUsersRepositoryMockRecorder struct {
	mock *MockIUsersRepository
}

// NewMockIUsersRepository creates a new mock instance.
func NewMockIUsersRepository(ctrl *gomock.Controller) *MockIUsersRepository {
	mock := &MockIUsersRepository{ctrl: ctrl}
	mock.recorder = &MockIUsersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsersRepository) EXPECT() *MockIUsersRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIUsersRepository) Create(arg0 *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIUsersRepositoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUsersRepository)(nil).Create), arg0)
}

// Get mocks base method.
func (m *MockIUsersRepository) Get(arg0 string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIUsersRepositoryMockRecorder) Get(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIUsersRepository)(nil).Get), arg0)
}

// Update mocks base method.
func (m *MockIUsersRepository) Update(arg0 string, arg1 *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIUsersRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUsersRepository)(nil).Update), arg0, arg1)
}
